# Generated by Django 5.0.2 on 2024-04-29 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_remove_product_discount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('id',), 'verbose_name': 'Тип абонемента', 'verbose_name_plural': 'Типы абонементов'},
        ),
        migrations.AddField(
            model_name='product',
            name='validity_period',
            field=models.PositiveIntegerField(default=0, verbose_name='Срок действия'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.PositiveIntegerField(default=0, verbose_name='Стоимость'),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество доступных занятий'),
        ),
    ]
