# Generated by Django 5.0.2 on 2024-05-01 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('direction', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FitnessClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_date', models.DateTimeField(verbose_name='Дата и время занятия')),
                ('instructor', models.CharField(max_length=150, verbose_name='Инструктор')),
                ('place', models.CharField(max_length=150, verbose_name='Место проведения занятия')),
                ('number', models.PositiveIntegerField(default=0, verbose_name='Количество свободных мест на занятие')),
                ('direction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='direction.direction', verbose_name='Направление')),
            ],
            options={
                'verbose_name': 'Занятие',
                'verbose_name_plural': 'Занятия',
                'db_table': 'schedule',
                'ordering': ('class_date',),
            },
        ),
    ]
