# Generated by Django 5.0.2 on 2024-05-07 15:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_product_options_product_validity_period_and_more'),
        ('direction', '0003_instructor_alter_fitnessclass_instructor'),
        ('orders', '0003_orderitem_membership_start_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Дата начала действия')),
                ('end_date', models.DateField(verbose_name='Дата окончания действия')),
                ('number', models.PositiveIntegerField(verbose_name='Количество доступных занятий')),
                ('order_item', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='orders.orderitem', verbose_name='Заказ')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.product', verbose_name='Тип абонемента')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Клиент')),
            ],
        ),
    ]
