# Generated by Django 5.0.2 on 2024-05-07 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('direction', '0004_membership'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='membership',
            options={'verbose_name': 'Абонемент', 'verbose_name_plural': 'Абонементы'},
        ),
        migrations.AlterModelTable(
            name='membership',
            table='membership',
        ),
    ]
