# Generated by Django 5.0.2 on 2024-05-07 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('direction', '0005_alter_membership_options_alter_membership_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата окончания действия'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='number',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Количество доступных занятий'),
        ),
    ]
