# Generated by Django 5.0.2 on 2024-05-07 23:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('direction', '0006_alter_membership_end_date_alter_membership_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='end_date',
            field=models.DateField(default=None, verbose_name='Дата окончания действия'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='number',
            field=models.PositiveIntegerField(default=None, verbose_name='Количество доступных занятий'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Клиент'),
        ),
    ]
