# Generated by Django 5.0.2 on 2024-05-07 23:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('direction', '0007_alter_membership_end_date_alter_membership_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fitnessclass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='direction.fitnessclass', verbose_name='Занятие')),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='direction.membership', verbose_name='Абонемент')),
            ],
            options={
                'verbose_name': 'Запись',
                'verbose_name_plural': 'Записи',
                'db_table': 'record',
            },
        ),
    ]
