# Generated by Django 5.0.2 on 2024-05-06 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_order_delivery_address_remove_order_is_paid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='membership_start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата начала действия абонемента'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='created_timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата заказа'),
        ),
    ]
